### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Th3-DoC**
## Description

Please include a summary of the change and which issue is fixed.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the docstring for new or existing methods
- [ ] I have modified this PR to merge to the develop branch

### CODE REVIEW

**Comment by Th3-DoC** [comment]
# Any Code Edits Are Marked for Review.
# Fixed issue with qBm removing share tags randomly with large amounts of torrents 1k+
Added Features:
-Allow categories to handle downloads.
-Allow share limit tags to handle downloads.
-Allow removal of priority from share limit tags.
-Allow Edit of share limit grouping tags name/visibility.
-Set Suffix of share limit group tags.
-Allow qBm paused group tag to help prevent unwanted cleanup.
-Allow removal of share limit tag when using share limit group tag.

**Comment by bakerboy448** [comment]
Which GHIs does this address

**Comment by Th3-DoC** [comment]
It maybe associated with "[Bug]: Share limit tags do not update #457" however I do not use any noHL torrents/tags though I intend on fiddling with these in the near future, I can't say for certain. However in my own extensive testing of the original qBm version and my own I noticed occasionally qBm will not re-register the group share_tag and it will be removed from the tag when added to one of the grouping tags MIN_SEEDING_TIME_TAG, MIN_NUM_SEEDS_TAG or LAST_ACTIVE_TAG for whatever reason I didn't run across the issue with under 100 torrents in qBt only with large amounts at 1K plus.

**Comment by Th3-DoC** [comment]
I realized that dry_run capabilities for the _has_paused() definition in has_reached_seed_limit() wasn't setup and have since commited a few changes for this as well as config calls are now completed in the __init__() which lowered run time considerably with my high torrent counts of 1k+ I also changed the format of my # EDIT # comments that cause the workflow issues with pre-commit.ci

**Comment by Th3-DoC** [comment]
I have some work todo cleaning up the code, I have an almost working version with half the code and "proper workflow" with adding tags etc. now that I understand qBm's "code flow" if I may haha. I've got much more experience with java but want to tie them together in some future projects with java's now open source implementations, so I'm looking to further my understanding of it. Really do love it's implementation, it has great versatility built in! Great seeing the complete/incomplete filter official! It seems there was a decent amount of interest! I've also found a neat and simple implementation idea for more seeding options within the share_limits for some requested features and my needs with active download's/inactive torrents. Falling in love with python though not gunna lie! little one liner in the util.get_list() definition opens up a lot of versatility with the config data. I'd like to make it possible for them to add there own variations and have qBm read it so long as there within a "spec" which would allow different limits/settings per torrent within the same group based on there input. That's down the road a bit though haha still a lot more for me to navigate and understand with "workflow" and there current purposes before metaling around with them haha. Talk soon I'm sure :)

**Pull request closed without merging**
