### PR TITLE
Update mover.py: add optional arg --status-filter to allow fine tune which torrents to pauseUpdate mover.py: add optional arg --status-filter to allow fine tune which torrents to pause

### PR DESCRIPTION
**Pull request by convexshiba**
## Description

add optional arg --status-filter to allow fine tune which torrents to pause
useful when only wish to pause seeding torrents but not downloading ones.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by bobokun** [comment]
I'm not sure I understand the use case for this. When would you want to leave a torrent unpaused when running the mover script? If a torrent is not paused then the torrent won't be able to be moved by mover if the files are in use.

**Comment by convexshiba** [comment]
> I'm not sure I understand the use case for this. When would you want to leave a torrent unpaused when running the mover script? If a torrent is not paused then the torrent won't be able to be moved by mover if the files are in use.

The situation I run into is that if there are a significant amount of torrents still downloading, pausing them will lead all files to be moved to disk. Then after resume qbittorrent will then continue to download directly into disk for an extended period of time.

By only limiting pausing `downloading` torrents, this will lead to only these to moved
- Finished torrents
- Completed files of `downloading` torrents that are not being read

These are only going to be read-only after being moved.

So this way the hard drive will host read-heavy files and writes will still be done into Cache as much as possible.

This has another, albeit minor, advantage when harddrive array writes speed are slower than cache write speed.

**Comment by bobokun** [comment]
okay, makes sense. Can you make the default 'completed' instead of None? I think in general most people would want to leave downloading torrents in cache like you mentioned.

**Comment by convexshiba** [comment]
> okay, makes sense. Can you make the default 'completed' instead of None? I think in general most people would want to leave downloading torrents in cache like you mentioned.

Sure thing. I think moving "all" is still a valid use case, but it's easily changeable both ways.

seems we both changed it. not sure how to get my commit removed from PR.

**Review by bobokun — APPROVED** [review]

**Pull request merged**
