### PR TITLE
Add new torrent webhook

### PR DESCRIPTION
**Pull request by buthed010203**
## Description
Adds a webhook for new torrents similar to cross-seed, this currently allows for tags and share ratios to be set either on torrent addition or completion. Default port of 2469 is the cross-seed port + 1 since lots of people are already using cross-seed and this is a similar type of QoL application

Various TODO items remain throughout the code and must be addressed before this PR is merged, a few of them as well as some others here:
- [ ] Docs need updating, to include the feature. It's important to mention to the user that they should not expose the api as it has no authentication
- [ ] Webhook path and settings are not final, couldn't think of anything better than what I have
- [ ] Still needs command line and env var toggles
- [ ] The settings could use a lookover as I didn't bother to figure out how half of the params work
- [ ] Still needs testing with the settings missing from the config file to ensure nothing explodes
- [ ] The webserver should only ever start once, that is not currently the case

## Type of change
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the docstring for new or existing methods
- [ ] I have added tests when applicable

### CODE REVIEW

**Comment by buthed010203** [comment]
This happens to include the stuff from 299 as I was using that as the base branch for this pr

**Comment by bakerboy448** [comment]
rebase on upstream; don't merge

**Comment by buthed010203** [comment]
I ended up changing a bunch of stuff here too, it's mostly minor fixes but I should really put it on its own branch

**Comment by buthed010203** [comment]
This has just become my own fork at this point considering how many things this branch changes. The PR is way out of scope so I'm just going to close it. I should probably still PR most of these changes though considering they fix or improve various things...

**Pull request closed without merging**
