### PR TITLE
Script to delete torrents on low disk space

### LINKED ISSUE #163: [FR]: Clean up torrents based on disk space
### Is your feature request related to a problem? Please elaborate.

To seed torrents as long as physically possible, torrents should be deleted only once low on space. Seed ratio and time either deletes while there is plenty of space or doesn't when there is no space.

### Describe the solution you'd like

Check if disk usage is below user defined amount. I wrote a completely separate script for myself and it works flawlessly. It would be nice for others to have it as well.

### Does your solution involve any of the following?

- [X] New config option
- [X] New command option

### Describe alternatives you've considered

There are no alternatives.

### Who will this benefit?

Everyone who has ever used a torrent, not just qbit_manage users. Torrents will stay seeded until they can't.

### Additional Information

Here is my implementation. Use a while loop on is_storage_full(), deleting a torrent each iteration.

Code Snippet

### PR DESCRIPTION
**Pull request by StoneColeQ**
## Description

Please include a summary of the change and which issue is fixed.

Added ability to delete torrents only when low on disk space.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the docstring for new or existing methods
- [x] I have added tests when applicable

### CODE REVIEW

**Comment by BaukeZwart** [comment]
Tried the script, but I'm getting the following error.
```
Traceback (most recent call last):
  File "delete_torrents_on_low_disk_space.py", line 69, in <module>
    def get_disk_usage() -> tuple[float, float]:
TypeError: 'type' object is not subscriptable
```

**Comment by StoneColeQ** [comment]
@BaukeZwart I forgot about that. Those type annotations are for python 3.10+ which probably isn't being used. Should be a quick fix.

**Comment by StoneColeQ** [comment]
@bobokun Created a PR with fix #177

**Comment by BaukeZwart** [comment]
@StoneColeQ Thanks for the fix. I will try it asap and report back.

**Comment by gennaios** [comment]
Nice script. Any chance there could be more options such as limiting seed size per tracker? I’d like to auto delete those above some ratio only if total seed size for some tracker is above some size. 
 
As I wish to manage seed size per tracker as a different way to ensure some minimum free space.

**Comment by ShanaryS** [comment]
@gennaios I can allow you to specify trackers but what do you mean by seed size? Number of seeders?

P.S I'm the one who wrote the script, now on my main account.

**Comment by LimeDrive** [comment]
Hi @ShanaryS 

Seen this tread by following qbt_manage

I've the same kind of project than your script with scoring on torrent selection following ratio, seedtime etc... : https://github.com/LimeDrive/QbAutoDelt 
i'm planing to improve that script ( by also rm cross-seed torrent related and add move option ) for my need.

I'm not a python expert, just script kiddie but i will be happy to collaborate on that, to make a proper code.
Please feel free to contact me if you're interested.

**Comment by gennaios** [comment]
@ShanaryS 

Thank you for the consideration. 

I mean total size of torrents seeded for a particular tracker. As I use RSS or other to autodownload torrents, I wish to automatically remove older ones above some ratio and seeding time to keep total seeded torrent size below some value. A way to maintain some amount of free space yet by instead specifying total torrent size per tracker. 

There is also this which is fairly flexible but doesn’t quite do what I wish. One can specify multiple criteria but it’s seed_size is unique ignoring all else.

https://github.com/jerrymakesjelly/autoremove-torrents

I’m not sure how common of a task such is and how many would use such but something very configurable or perhaps that can grow into such sure would be great.

**Comment by ShanaryS** [comment]
@LimeDrive Thanks for letting me know. Unfortunately I'm working on few scripts right now and don't have time for another. Hopefully everything can be sorted out.

@gennaios I'll look into it. Currently thinking of setting a limit for all trackers but I'll see if it makes sense to allow specifying trackers.

**Comment by ShanaryS** [comment]
@gennaios I made a PR of the changes #189. It gives the option to delete torrents that have trackers above the size limit first. Note, it will only delete those torrents once the disk space is below the config amount. I know this may not be what you wanted but doing it any other way changes the core philosophy of the script.

**Comment by ShanaryS** [comment]
@gennaios I add the option to dry run #189. You can just copy the file: https://github.com/StuffAnThings/qbit_manage/blob/63b7f42b2f2da402add2801f0fd968492b2d8225/scripts/delete_torrents_on_low_disk_space.py

**Comment by gennaios** [comment]
@ShanaryS thank you very much. I’ll give it a try.

**Comment by gennaios** [comment]
@ShanaryS I’ve had a chance to try the script. Modifying for my purposes, it works great. 

A few things I believe you might have missed. I think line 118 `setup_services()` isn’t necessary? Authentication is also not using username and password as I believe you may have authentication for localhost as not required. Other than that, all is great.

**Comment by ShanaryS** [comment]
@gennaios I have authentication for localhost on, for my script I don't use username and password. But I left in there just in case. the setup_services() used to do more but I removed a lot, didn't want to refactor.

**Pull request merged**
